" Add custom config directory to runtime path
" Get the directory of this vimrc file (which contains the colors subdirectory)
let s:config_dir = fnamemodify(resolve(expand('<sfile>:p')), ':h')
let &runtimepath = s:config_dir . ',' . &runtimepath

" Use a Printer-Friendly Color Scheme
" print_bw: Black & white scheme using bold/italic for syntax highlighting
" Perfect for monochrome printers, avoiding gray shades
colorscheme print_bw 

" tabs and spaces handling
set expandtab
set tabstop=4
set shiftwidth=4
set encoding=utf-8
set fileencoding=utf-8
set printoptions=number:y
set guifont=Noto\ Sans\ Simplified\ Chinese

" Configure CJK (Chinese/Japanese/Korean) font for printing
set printmbcharset=GB_2312-80
set printmbfont=r:Noto\ Sans\ SC

" Enable syntax highlighting
syntax on

" Automatically detect file type
filetype on
filetype indent on
filetype plugin on
