" Use a Printer-Friendly Color Scheme
colorscheme zellner 

" tabs and spaces handling
set expandtab
set tabstop=4
set shiftwidth=4
set encoding=utf-8
set fileencoding=utf-8
set printoptions=number:y
set guifont=Noto\ Sans\ Simplified\ Chinese

" Configure CJK (Chinese/Japanese/Korean) font for printing
set printmbcharset=GB_2312-80
set printmbfont=r:Noto\ Sans\ SC

" Enable syntax highlighting
syntax on

" Automatically detect file type
filetype on
filetype indent on
filetype plugin on
